# Generated by Django 5.1.4 on 2024-12-23 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_customuser_is_admin_alter_customuser_is_staff"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="status",
            new_name="isOnline",
        ),
    ]
