# Generated by Django 5.1.4 on 2025-02-02 14:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_rename_status_customuser_isonline"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="friends",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="customuser",
            name="pendingRequest",
            field=models.ManyToManyField(
                blank=True,
                related_name="received_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="requested",
            field=models.ManyToManyField(
                blank=True, related_name="sent_requests", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
