# Generated by Django 5.1.7 on 2025-03-23 15:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagetracker',
            name='messageTrackerID',
            field=models.UUIDField(default=uuid.UUID('0ab65b15-a706-4e14-ae35-9913052bc25e'), editable=False, primary_key=True, serialize=False),
        ),
    ]
