# Generated by Django 5.1.7 on 2025-03-23 15:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_messagetracker_messagetrackerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagetracker',
            name='messageTrackerID',
            field=models.UUIDField(default=uuid.UUID('4695cd1a-d2fd-4d33-83f8-5c2e72e42aed'), editable=False, primary_key=True, serialize=False),
        ),
    ]
