# Generated by Django 5.1.7 on 2025-03-23 16:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_messagetracker_messagetrackerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagetracker',
            name='messageTrackerID',
            field=models.UUIDField(default=uuid.UUID('f192150a-0cfc-4d28-915e-f55f719598c5'), editable=False, primary_key=True, serialize=False),
        ),
    ]
