# Generated by Django 5.1.7 on 2025-05-10 10:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_messagetracker_messagetrackerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagetracker',
            name='messageTrackerID',
            field=models.UUIDField(default=uuid.UUID('f7f8b541-37fd-4acb-be1e-26f7de8e01b8'), editable=False, primary_key=True, serialize=False),
        ),
    ]
