# Generated by Django 5.1.7 on 2025-03-23 16:35

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(default='1742747145/default.jpg', max_length=255, verbose_name='1742747145/image'),
        ),
    ]
